# Generated by Django 5.1.4 on 2025-01-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(default='Default Todo Item'),
            preserve_default=False,
        ),
    ]
